"""Bakåtkompatibel fasad för det uppdelade paketet app.backend.data_fetch.

Implementationen bor i app/backend/data_fetch/ (core, catalog, plan, segments,
engine, present). Importera gärna direkt från paketet i ny kod. Tester som
monkeypatchar interna namn ska patcha implementationsmodulen, inte fasaden.
"""
from .config import settings
from .data_fetch import catalog, core, engine, plan, present, segments

from .data_fetch.core import (
    ALLOWED_CALCULATION_METRICS,
    ALLOWED_OPERATORS,
    CALCULATION_METRIC_ALIASES,
    CODE_VALUE_COLUMNS,
    DATE_COLUMN_PRIORITY,
    DEFAULT_CATALOG_PATH,
    DataCatalog,
    DataColumn,
    DataFetchConfigError,
    DataFetchPlanError,
    DataView,
    LOCAL_FILTER_OPERATORS,
    MONTH_ALIASES,
    MONTH_PATTERN,
    OPERATOR_ALIASES,
    PACKAGE_ALIAS_COMPANY_FIELD,
    PACKAGE_ALIAS_FACTOR_FIELD,
    PACKAGE_ALIAS_ITEM_FIELD,
    PACKAGE_ALIAS_UNIT_FIELD,
    PACKAGE_ALIAS_VIEW,
    PACKAGE_BASE_UNIT_LABEL,
    PACKAGE_JOIN_COMPANY_FIELD,
    PACKAGE_JOIN_ITEM_FIELD,
    PACKAGE_UNIT_RESULT_FIELD,
    PREFERRED_DATE_COLUMNS_BY_VIEW,
    RELATIVE_DAYS_PATTERN,
    ROOT_DIR,
    STOP_WORDS,
    TEXT_FILTER_OPERATORS,
    TODAY_PATTERN,
    _app_now,
    _compact_number,
    _date_period_payload,
    _match_score,
    _normalize,
    _normalize_filter_value,
    _number_value,
    _period_values_for_column,
    _preferred_date_column,
    _row_value,
    _stable_value_key,
    _tokens,
    infer_prompt_period,
)
from .data_fetch.catalog import (
    _catalog_source,
    build_catalog_context,
    catalog_from_payload,
    catalog_summary,
    clear_catalog_cache,
    load_catalog,
)
from .data_fetch.plan import (
    _assert_column,
    _column_id_list,
    _identifiers_are_column_list,
    _normalize_calculation,
    _normalize_calculation_metric,
    _normalize_filters,
    _normalize_identifiers,
    _normalize_operator,
    _normalize_output_columns,
    _normalize_sort_by,
    apply_prompt_period_hint,
    build_data_fetch_minimax_payload,
    parse_minimax_plan,
    validate_plan_payload,
)
from .data_fetch.segments import (
    ARCHIVE_TO_LIVE,
    LIVE_ARCHIVE_PAIRS,
    _parse_plan_date_bound,
    _plan_date_window,
    _segment_plan,
    build_retention_segments,
)
from .data_fetch.engine import (
    _calculation_label,
    _compare_values,
    _like_pattern_to_regex,
    _local_filter_matches,
    _metric_value,
    _package_factor,
    _values_equal,
    apply_local_filters,
    build_package_ladders,
    execute_calculation,
    execute_package_breakdown,
    external_filters_for_api,
    plan_with_default_calculation,
    project_rows,
    split_quantity_into_packages,
)
from .data_fetch.present import (
    _like_pattern_for_operator,
    _sql_literal,
    _sql_metric_expression,
    _sql_where_clauses,
    calculation_query_text,
    columns_for_response,
)
