"""Bakåtkompatibel fasad för det uppdelade paketet app.backend.sankey_inbound.

Implementationen bor i app/backend/sankey_inbound/ (common, cache, trace, rows,
build, fetch, service). Importera gärna direkt från paketet i ny kod. Tester som
monkeypatchar interna namn ska patcha implementationsmodulen, inte fasaden.
"""
from . import local_archive_store
from .config import settings
from .data_fetch_service import (
    ARCHIVE_TO_LIVE,
    DataFetchConfigError,
    DataFetchPlanError,
    LIVE_ARCHIVE_PAIRS,
    PACKAGE_ALIAS_VIEW,
    PACKAGE_BASE_UNIT_LABEL,
    build_package_ladders,
    load_catalog,
    split_quantity_into_packages,
)
from .external_data_client import ExternalDataClient, ExternalDataClientError
from .productivity_service import find_kpi_file
from .productivity_sync import productivity_snapshot_status
from .sankey_inbound import build, cache, common, fetch, rows, service, trace

from .sankey_inbound.common import (
    BUFFER_UPDATE_RECEIVE_TYPE,
    CLIENT_FILTER_PREBUILD_MAX_SOURCE_ROWS,
    CLIENT_FILTER_PREBUILD_MAX_VIEWS,
    CURRENT_STATE_SOURCE_KEYS,
    DEGRADABLE_SOURCE_KEYS,
    EXCLUDED_RECEIVE_TYPES,
    INBOUND_LABEL_ROW_ID,
    INBOUND_PURCHASE_LINE_ROW_ID,
    OPEN_STATUS_LABELS,
    OUTBOUND_ECOM_ORDER_PREFIX,
    OUTBOUND_METRICS,
    OUTBOUND_STORE_ORDER_PREFIX,
    PERIOD_ONLY_SOURCE_KEYS,
    PROCESS_DEFAULT_METRIC,
    PROCESS_LABELS,
    PROCESS_POINT_ALIASES,
    PRODUCTIVITY_SNAPSHOT_REUSE_SOURCE_KEYS,
    PickQueueEntry,
    ProcessVisit,
    ProgressCallback,
    REQUIRED_SOURCE_KEYS,
    SANKEY_SOURCE_VIEWS,
    SOURCE_LABELS,
    SankeyInboundError,
    TraceBranch,
    ZEROING_RECEIVE_TYPE,
    _emit_progress,
)
from .sankey_inbound.cache import (
    SANKEY_INBOUND_PAYLOAD_SCHEMA,
    _CACHE,
    _SOURCE_CACHE,
    _cache_key,
    _get_cached_sankey_sources,
    _set_cached_sankey_sources,
    _source_cache_key,
    get_cached_sankey_payload,
    set_cached_sankey_payload,
)
from .sankey_inbound.trace import (
    _TRACE_CACHE,
    _csv_cell,
    _prune_trace_cache,
    _trace_date,
    compute_trace_counts,
    filter_trace_rows,
    get_trace_rows,
    store_trace_rows,
    trace_rows_to_csv_lines,
)
from .sankey_inbound.rows import (
    _clean_text,
    _client_filter_period_specs,
    _client_filter_view_key,
    _company_allowed,
    _inbound_prices,
    _invoice_row_prices,
    _is_in_date_window,
    _normalize_pall,
    _normalize_type,
    _order_starts_with,
    _outbound_prices,
    _outbound_trace_row,
    _pall_aliases,
    _parse_datetime,
    _period_label,
    _purchase_line_key,
    _round_money,
    _round_qty,
    _row_company,
    _row_datetime,
    _row_id,
    _row_item,
    _row_number,
    _row_order_number,
    _row_pall,
    _row_parent_pick_pall,
    _row_pick_pall,
    _row_pick_zone,
    _row_picked_qty,
    _row_purchase_line,
    _row_purchase_number,
    _row_text,
    _row_value,
    _row_warehouse,
    sankey_period_bounds,
)
from .sankey_inbound.build import (
    _add_link,
    _add_node,
    _append_process,
    _branch_matches_pall,
    _build_current_pallet_locations,
    _build_outbound_sankey,
    _classify_trans,
    _consume_pick_queue,
    _event_sort_key,
    _finalize_sankey,
    _minimal_trace_row,
    _node_id,
    _normalize_process_point_key,
    _pick_location_key,
    _process_point_value,
    _process_points_from_kpi,
    _status_from_current_location,
    _sync_branch_revenue,
    _trace_path_steps,
    _trace_row_for_branch,
    build_sankey_inbound_payload,
)
from .sankey_inbound.fetch import (
    _api_client,
    _company_filter,
    _date_filter_for_view,
    _date_span,
    _degraded_source_warning,
    _fetch_item_alias_rows,
    _fetch_productivity_snapshot_rows,
    _fetch_segment_rows,
    _fetch_segment_rows_with_source,
    _fetch_snapshot_rows,
    _fetch_view_rows,
    _iso,
    _load_kpi_fallback_rows,
    _query_local_archive_segment,
    _segment_kind,
    _segments_for_view,
    _source_failure_message,
    fetch_sankey_inbound_sources,
)
from .sankey_inbound.service import (
    _attach_trace_token,
    _client_filter_payloads,
    _set_trace_metadata,
    _trace_filter_for_payload,
    load_sankey_inbound_payload,
)
