"""In-house-motor för lagerflödena (ersätter vendor/allokering12.1.py).

Hela namnrymden re-exporteras så fasaden warehouse_tools.engine och flows
kan nå funktionerna som attribut, precis som mot den gamla vendormodulen.
"""
from __future__ import annotations

from ..vendor.app_info import APP_NAME, APP_TITLE, APP_VERSION
from .constants import (
    LOWFREQDATA_DIR,
    BUFFERPALL_DIR,
    BUFFERPALL_PATH_PARTS,
    DEFAULT_OBSERVATIONS_BUSINESS_CODE,
    INVALID_LOC_PREFIXES,
    INVALID_LOC_EXACT,
    ALLOC_BUFFER_STATUSES,
    REFILL_BUFFER_STATUSES,
    ORDER_MAX_ALLOCATABLE_STATUS,
    VECKA27_ROOF_TO_MOWERS,
    NEAR_MISS_PCT,
    RF_PALLPLATS_EXCLUDE_ARTICLES,
    ORDER_SCHEMA,
    BUFFER_SCHEMA,
    NOT_PUTAWAY_SCHEMA,
    SALDO_SCHEMA,
    ITEM_SCHEMA,
    ORDERSALDO_COLUMN_CANDIDATES,
    PAFYLLNADSPRIO_COLUMNS,
    LASTNINGSFONSTER_PRIO_COLUMNS,
    LASTNINGSFONSTER_UNKNOWN_SORT,
    LASTNINGSFONSTER_UNKNOWN_LABEL,
)
from .runtime_paths import (
    _app_config_path,
    _bundle_root,
    _runtime_root,
    _resource_path,
    _bufferpall_resource_path,
    _bufferpall_runtime_dir,
    _normalise_observations_business_code,
    _business_path_segment,
    _business_bufferpall_runtime_dir,
    _business_bufferpall_resource_path,
    _legacy_default_bufferpall_resource_path,
    _seed_bufferpall_runtime_file,
)
from .io_utils import (
    read_prognos_xlsx,
    read_campaign_xlsx,
    _clean_columns,
    smart_to_datetime,
    to_num,
    find_col,
    normalize_not_putaway,
    normalize_saldo,
    normalize_items,
    reclassify_skrymmande,
)
from .hib import (
    _hib_orders_with_today_origin,
    compute_hib_koppling,
    compute_missed_departures,
)
from .ordersaldo import (
    _find_lyx_max_csv,
    _ordersaldo_norm,
    _ordersaldo_find_col,
    _find_ordersaldo_columns,
    compute_ordersaldo_data,
    _build_article_max_map,
    _classify_pafyllnadsprio,
    _build_pafyllnadsprio_dataframe,
    build_pafyllnadsprio_report,
    _combine_orderdatum_and_laststart,
    _format_lastningsfonster_label,
    _prepare_lastningsfonster_overview,
    _build_lastningsfonster_prio_dataframe,
    build_pafyllnadsprio_lastningsfonster_report,
    utbest_per_article,
    compute_lyx_articles,
)
from .observations import (
    OBSERVATIONS_FILENAME,
    OBSERVATIONS_COLS,
    GITHUB_REPO,
    GITHUB_OBS_BRANCH,
    GITHUB_OBS_DIR,
    _observations_path,
    _artikel_max_path,
    _ensure_empty_observations,
    _ensure_empty_artikel_max,
    business_observations_path,
    business_artikel_max_path,
    ensure_business_allocation_data_files,
    _github_business_dir,
    _read_observations,
    _max_utan_outlier,
    _recompute_artikel_max,
    _read_artikel_max,
    _normalise_artikel_max_for_compare,
    _same_article_max_value,
    _format_article_max_value,
    _artikel_max_change_summary,
    update_observations_from_buffer,
    _github_token_path,
    _load_github_token,
    _github_request,
    push_new_observations_to_github,
    fetch_observations_from_github,
)
from .allocation import (
    compute_pallet_spaces,
    _safe_str_series,
    _str_to_num,
    _num_series,
    _collect_exclude_source_ids,
    build_prognos_vs_autoplock_report,
    allocate,
    calculate_refill,
)
from .reports import (
    OverviewCheckResult,
    DispatchCheckResult,
    Vecka27CheckResult,
    PrognosReportResult,
    ChunkedValuesResult,
    ObservationsUpdateResult,
    ObservationsSyncResult,
    UpdateCheckCliResult,
    _vecka27_fmt_qty_value,
    _find_keywords_column,
    _find_customer_name_column,
    _status_to_int,
    _build_order_to_customer_map,
    _empty_prognos_df,
    _normalize_prognos_cli_table,
    _normalize_campaign_cli_table,
    _load_prognos_cli_source,
    _load_campaign_cli_source,
    _combine_prognos_and_campaign,
    _validate_prognos_report_saldo,
    build_prognos_report_result,
    build_chunked_values_result,
    build_observations_update_result,
    build_observations_sync_result,
    _build_update_session_from_release_json,
    build_update_check_cli_result,
    _build_overview_check_sheets,
    build_overview_check_result,
    build_dispatch_check_result,
    build_vecka27_check_result,
)
from .filetypes import (
    detect_file_type,
    _read_cli_table,
    _df_with_named_index,
    _merge_item_flags,
    _resolve_max_csv_path,
    _read_cli_text_lines,
)
